{% set name = "manimpango" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ManimPango-{{ version }}.tar.gz
  sha256: a3a7e5a417507e9ccf307f6da40291a9fc2757a3c9a04de33dd18e92f63fcc25

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.27
    - pip
    - pango
    - cairo
    - glib
    - pkg-config
  run:
    - python
    - pango
    - cairo
    - glib

test:
  imports:
    - manimpango
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://manimpango.manim.community/
  summary: Bindings for Pango for using with Manim.
  dev_url: https://github.com/ManimCommunity/manimpango
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
