context:
  version: "0.7.0"

package:
  name: manimpango
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/manimpango/manimpango-${{ version }}.tar.gz
  sha256: 64330c360f5040ed356b9eb289d52e8ae8cbc3d9c39297c5e77522e1b417f1c7

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3.0.2,<3.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - pkg-config
  host:
    - python
    - setuptools
    - cython >=3.0.2,<3.1
    - pip
    - pango
    - cairo
    - glib
    - zlib
    - harfbuzz
    - freetype
    - fontconfig
    - expat
    - if: linux
      then:
        - xorg-xproto
        - xorg-kbproto
        - xorg-xextproto
        - xorg-renderproto
  run:
    - python
    - pango
    - cairo
    - glib

tests:
  - python:
      imports:
        - manimpango
      pip_check: true

about:
  homepage: https://manimpango.manim.community/
  summary: Bindings for Pango for using with Manim.
  repository: https://github.com/ManimCommunity/manimpango
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - pavelzw
